version: 3.8.0
services:
    web-youtubedl:
        working_dir: /home/web-youtubedl
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web-youtubedl
        ports:
            - 9156:80
        environment:
            - NODE_ENV=development